name: include paths

on:
  push:
    paths:
      - "backend/*"

jobs:

  hello-backend:
    runs-on: ubuntu-latest
    name: Simple gretting backend
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello backend"
