name: learn-github-actions

on:
  push:
    paths:
      - 'backend/'
      - '**/learn-github-actions.yml'
  workflow_dispatch:

env:
  BACKEND_DIR: 'backend/'

jobs:

  secrets-analysis:
    runs-on: ubuntu-latest
    name: Analisys secrets
    steps:
      - uses: actions/checkout@v2
      - name: trufflehog scaning
        run: |
          docker run --rm -v "$(pwd):/proj" dxa4481/trufflehog --regex -x .trufflehog file:///proj
          exit 0
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: trufflehog-scan
          path: trufflehog-scan.txt

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working_directory: ${{ env.BACKEND_DIR }}
        run: |
          npm ci
          ls

  check-bats-version:
    runs-on: ubuntu-latest
    name: checking bats package version
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

  example-job:
    runs-on: ubuntu-latest
    name: Save output
    steps:
      - shell: bash
        run: |
          echo "hello humans.!" > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log

  example-secrets:
    runs-on: ubuntu-latest
    name: example job to define secrets
    steps:
      - name: Retrieve secret
        env:
          super_secret: ${{ secrets.SUPERSECRET }}
        run: |
          echo "$super_secret"

