name: learn-github-actions

on:
  push:
    paths:
      - 'backend/'
  workflow_dispatch:

jobs:

  secrets-analysis:
    runs-on: ubuntu-latest
    name: Analisys secrets
      - uses: actions/checkout@v2
      - name: trufflehog scaning
        run: docker run --rm -v "$(pwd):/proj" --regex dxa4481/trufflehog file:///proj
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: trufflehog-scan
          path: trufflehog-scan.txt

  check-bats-version:
    runs-on: ubuntu-latest
    name: checking bats package version
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

  example-job:
    runs-on: ubuntu-latest
    name: Save output
    steps:
      - shell: bash
        run: |
          echo "hello humans.!" > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log

  example-secrets:
    runs-on: ubuntu-latest
    name: example job to define secrets
    steps:
      - name: Retrieve secret
        env:
          super_secret: ${{ secrets.SUPERSECRET }}
        run: |
          echo "$super_secret"

  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "setup project..."
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "building..."
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "testing..."
