name: learn-github-actions

on: [push]

jobs:

  runs-on: ubuntu-latest

  check-bats-version:
    name: checking bats package version
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

  example-job:
    name: Save output
    steps:
      - shell: bash
        run: |
          echo "hello humans.!" > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log

  example-secrets:
    name: example job to define secrets
    steps:
      - name: Retrieve secret
        env:
          super_secret: ${{ secrets.SUPERSECRET }}
        run: |
          example-command "$super_secret"
